server:
  port: 5050
  
 

spring:
  application:
    name: payment-service-client



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaulttZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


