server:
  port: 7070
  
spring:
  application:
    name: author-service-client



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaulttZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
